# Generated by Django 5.2.1 on 2025-08-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='deployment_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='live_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mock_interviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='notes_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='placement_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='source_code_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='student_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
    ]
